export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Dashboard } from './Dashboard';
export { default as Friends } from './Friends';
export { default as Goals } from './Goals';
export { default as GoalDetailPage } from './GoalDetailPage';
export { default as Profile } from './Profile';
export { default as FriendDetailPage } from './FriendDetailPage';
